# fly.toml app configuration file generated for ssl-sentinel-delicate-silence-8135 on 2025-02-19T20:24:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssl-sentinel-delicate-silence-8135'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
